### ISSUE TITLE
 Latest code on main branch didn't pass black formatter

### ISSUE THREAD

**Issue by vra** [leptonai/leptonai-sdk#65] opened 2023-09-21 16:23 UTC
**Describe the bug**
black code formatter runs failed on the codebase 

**To Reproduce**
```bash
git clone https://github.com/leptonai/leptonai-sdk
cd leptonai-sdk
pip install -e . 
pip install -e .[test]
pip install -e .[lint]
black .
git diff
```

**Expected behavior**
no file changed.

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: 3.8.17
 - LeptonAI sdk version: lep, version 0.9.8.post1.dev1+g500f37c
 - black version: 23.3.0 (compiled: yes)
 
**Additional context**

**Comment by Yangqing** [comment] 2023-09-21 18:01
Would you mind sharing the git diff output? I cannot reproduce on my side unfortunately. Also, could you try with `black --preview`?

**Comment by vra** [comment] 2023-09-22 00:23
@Yangqing

> Would you mind sharing the git diff output? I cannot reproduce on my side unfortunately. Also, could you try with `black --preview`?

Hi @Yangqing , This is an issue about the lower version of balck. When I upgrade black from 23.3.0 to 23.9.1, All files pass formatting without any change.

below is the output of black 23.3.0 on my macOS with python3.8.17.

the output of `black .`:
```bash
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/secret.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/storage.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/workspace.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/photon/tests/test_client_docgen.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/client.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/deployment.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/photon.py

All done! ✨ 🍰 ✨
7 files reformatted, 65 files left unchanged.
```
the output of git diff command after `black .`:
```diff
diff --git a/leptonai/cli/deployment.py b/leptonai/cli/deployment.py
index abd4865..f6ed657 100644
--- a/leptonai/cli/deployment.py
+++ b/leptonai/cli/deployment.py
@@ -96,8 +96,10 @@ def remove(name):
         response,
         f"Deployment [green]{name}[/] removed.",
         f"Deployment [yellow]{name}[/] does not exist.",
-        f"{response.text}\nFailed to remove deployment [red]{name}[/]. See error"
-        " message above.",
+        (
+            f"{response.text}\nFailed to remove deployment [red]{name}[/]. See error"
+            " message above."
+        ),
     )
     return 0
 
diff --git a/leptonai/cli/photon.py b/leptonai/cli/photon.py
index 9eb43cc..b66f979 100644
--- a/leptonai/cli/photon.py
+++ b/leptonai/cli/photon.py
@@ -179,11 +179,15 @@ def remove(name, local, id_, all_):
             explain_response(
                 api.remove_remote(conn, id_to_remove),
                 f"Photon id [green]{id_to_remove}[/] removed.",
-                f"Photon id [red]{id_to_remove}[/] not removed. Some deployments still"
-                " using it. Remove the deployments first with `lep deployment"
-                " remove`.",
-                f"Photon id [red]{id_to_remove}[/] not removed. See error message"
-                " above.",
+                (
+                    f"Photon id [red]{id_to_remove}[/] not removed. Some deployments"
+                    " still using it. Remove the deployments first with `lep"
+                    " deployment remove`."
+                ),
+                (
+                    f"Photon id [red]{id_to_remove}[/] not removed. See error message"
+                    " above."
+                ),
                 exit_if_4xx=True,
             )
         return
@@ -283,8 +287,10 @@ def _find_deployment_name_or_die(conn: Connection, name, id, deployment_name):
     existing_names = set(d["name"] for d in deployments)
     check(
         deployment_name not in existing_names,
-        f"Deployment [red]{deployment_name}[/] already exists. please"
-        " choose another name.",
+        (
+            f"Deployment [red]{deployment_name}[/] already exists. please"
+            " choose another name."
+        ),
     )
     if not deployment_name:
         console.print("Attempting to find a proper deployment name.")
@@ -450,8 +456,11 @@ def run(
             id = _get_most_recent_photon_id_or_none(conn, name)
             if not id:
                 console.print(
-                    f"Photon [red]{name}[/] does not exist in the workspace. Did you"
-                    " intend to run a local photon? If so, please specify --local.",
+                    (
+                        f"Photon [red]{name}[/] does not exist in the workspace. Did"
+                        " you intend to run a local photon? If so, please specify"
+                        " --local."
+                    ),
                 )
                 sys.exit(1)
             console.print(f"Running the most recent version of [green]{name}[/]: {id}")
@@ -480,12 +489,18 @@ def run(
             sys.exit(1)
         explain_response(
             response,
-            f"Photon launched as [green]{deployment_name}[/]. Use `lep deployment"
-            f" status -n {deployment_name}` to check the status.",
-            f"Failed to launch photon as [red]{deployment_name}[/]. See error"
-            " message above.",
-            f"Failed to launch photon as [red]{deployment_name}[/]. Internal server"
-            " error.",
+            (
+                f"Photon launched as [green]{deployment_name}[/]. Use `lep deployment"
+                f" status -n {deployment_name}` to check the status."
+            ),
+            (
+                f"Failed to launch photon as [red]{deployment_name}[/]. See error"
+                " message above."
+            ),
+            (
+                f"Failed to launch photon as [red]{deployment_name}[/]. Internal server"
+                " error."
+            ),
         )
     else:
         # local execution
diff --git a/leptonai/cli/secret.py b/leptonai/cli/secret.py
index f91a430..1305dc9 100644
--- a/leptonai/cli/secret.py
+++ b/leptonai/cli/secret.py
@@ -49,8 +49,10 @@ def create(name, value):
     for n in name:
         check(
             not n.lower().startswith(LEPTON_RESERVED_ENV_PREFIX),
-            "Secret name cannot start with reserved prefix"
-            f" {LEPTON_RESERVED_ENV_PREFIX}. Found {n}.",
+            (
+                "Secret name cannot start with reserved prefix"
+                f" {LEPTON_RESERVED_ENV_PREFIX}. Found {n}."
+            ),
         )
     conn = get_connection_or_die()
     existing_secrets = api.list_secret(conn)
@@ -58,9 +60,11 @@ def create(name, value):
         for n in name:
             check(
                 n not in existing_secrets,
-                f"Secret with name [red]{n}[/] already exists. Please use a"
-                " different name or remove the existing secret with `lep secret"
-                " remove` first.",
+                (
+                    f"Secret with name [red]{n}[/] already exists. Please use a"
+                    " different name or remove the existing secret with `lep secret"
+                    " remove` first."
+                ),
             )
     response = api.create_secret(conn, name, value)
     explain_response(
diff --git a/leptonai/cli/storage.py b/leptonai/cli/storage.py
index 1f7a593..442b189 100644
--- a/leptonai/cli/storage.py
+++ b/leptonai/cli/storage.py
@@ -125,8 +125,10 @@ def rm(path):
     check(file_type is not None, f"[red]{path}[/] not found")
     check(
         file_type != "dir",
-        f"[red]{path}[/] is a directory. Use [red]rmdir {path}[/] to delete"
-        " directories.",
+        (
+            f"[red]{path}[/] is a directory. Use [red]rmdir {path}[/] to delete"
+            " directories."
+        ),
     )
 
     explain_response(
diff --git a/leptonai/cli/workspace.py b/leptonai/cli/workspace.py
index c334feb..32ba402 100644
--- a/leptonai/cli/workspace.py
+++ b/leptonai/cli/workspace.py
@@ -59,25 +59,31 @@ def login(
                 matching_ids.append(workspace_id)
         check(
             len(matching_ids) > 0,
-            f"No workspace with the given display name [red]{display_name}[/]"
-            " exists. Please first log in to the workspace using `lep workspace"
-            " login -i <workspace-id>`.",
+            (
+                f"No workspace with the given display name [red]{display_name}[/]"
+                " exists. Please first log in to the workspace using `lep workspace"
+                " login -i <workspace-id>`."
+            ),
         )
         check(
             len(matching_ids) == 1,
-            "Multiple workspaces with the given display name"
-            f" [red]{display_name}[/] exists. Note that display names may not be"
-            " unique - in this case, please log in with the workspace id using"
-            " `lep workspace login -i <workspace-id>`.",
+            (
+                "Multiple workspaces with the given display name"
+                f" [red]{display_name}[/] exists. Note that display names may not be"
+                " unique - in this case, please log in with the workspace id using"
+                " `lep workspace login -i <workspace-id>`."
+            ),
         )
         workspace_id = matching_ids[0]
     if test_only_workspace_url:
         check(
             workspace_id,
-            "Must specify --workspace-id if using --test-only-workspace-url. This"
-            " will create a new workspace login with the given workspace url. Also,"
-            " you should only use this if you are running unit tests for the Lepton"
-            " SDK.",
+            (
+                "Must specify --workspace-id if using --test-only-workspace-url. This"
+                " will create a new workspace login with the given workspace url. Also,"
+                " you should only use this if you are running unit tests for the Lepton"
+                " SDK."
+            ),
         )
         console.print("Using test-only workspace url for internal testing purposes.")
         console.print("Do not use this option unless you know what you are doing.")
diff --git a/leptonai/client.py b/leptonai/client.py
index ca0d40b..f43b2c0 100644
--- a/leptonai/client.py
+++ b/leptonai/client.py
@@ -250,11 +250,13 @@ class Client(object):
         # Check healthz to see if things are properly working
         if not self.healthz():
             self._debug_record.append(
-                "Client is not healthy - healthz() returned False. This might be"
-                " due to:\n- a nonstandard deployment that does not have a healthz"
-                " endpoint. In this case, you may ignore this warning.\n- a network"
-                " error. In this case, please check your network connection. You"
-                " may want to recreate the client for things to work properly.",
+                (
+                    "Client is not healthy - healthz() returned False. This might be"
+                    " due to:\n- a nonstandard deployment that does not have a healthz"
+                    " endpoint. In this case, you may ignore this warning.\n- a network"
+                    " error. In this case, please check your network connection. You"
+                    " may want to recreate the client for things to work properly."
+                ),
             )
 
         # At load time, we will also load the openapi specification.
diff --git a/leptonai/photon/tests/test_client_docgen.py b/leptonai/photon/tests/test_client_docgen.py
index 83a738b..bd84c85 100644
--- a/leptonai/photon/tests/test_client_docgen.py
+++ b/leptonai/photon/tests/test_client_docgen.py
@@ -154,8 +154,10 @@ class TestClientDocgen(unittest.TestCase):
         except RuntimeError as e:
             error_str = str(e)
             self.assertIn(
-                "Did you mean the following?\n    run5(\n        query='hello',\n  "
-                "      query2=1,\n    )",
+                (
+                    "Did you mean the following?\n    run5(\n        query='hello',\n  "
+                    "      query2=1,\n    )"
+                ),
                 error_str,
             )
```

And the output of `black . --preview`:
```bash
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/secret.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/storage.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/photon/tests/test_client_docgen.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/workspace.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/client.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/deployment.py
reformatted /Users/yunfeng/ws/project/github/leptonai-sdk/leptonai/cli/photon.py

All done! ✨ 🍰 ✨
7 files reformatted, 65 files left unchanged.
```
git diff output after `black . --preview`:
```diff
diff --git a/leptonai/cli/deployment.py b/leptonai/cli/deployment.py
index abd4865..f6ed657 100644
--- a/leptonai/cli/deployment.py
+++ b/leptonai/cli/deployment.py
@@ -96,8 +96,10 @@ def remove(name):
         response,
         f"Deployment [green]{name}[/] removed.",
         f"Deployment [yellow]{name}[/] does not exist.",
-        f"{response.text}\nFailed to remove deployment [red]{name}[/]. See error"
-        " message above.",
+        (
+            f"{response.text}\nFailed to remove deployment [red]{name}[/]. See error"
+            " message above."
+        ),
     )
     return 0
 
diff --git a/leptonai/cli/photon.py b/leptonai/cli/photon.py
index 9eb43cc..b66f979 100644
--- a/leptonai/cli/photon.py
+++ b/leptonai/cli/photon.py
@@ -179,11 +179,15 @@ def remove(name, local, id_, all_):
             explain_response(
                 api.remove_remote(conn, id_to_remove),
                 f"Photon id [green]{id_to_remove}[/] removed.",
-                f"Photon id [red]{id_to_remove}[/] not removed. Some deployments still"
-                " using it. Remove the deployments first with `lep deployment"
-                " remove`.",
-                f"Photon id [red]{id_to_remove}[/] not removed. See error message"
-                " above.",
+                (
+                    f"Photon id [red]{id_to_remove}[/] not removed. Some deployments"
+                    " still using it. Remove the deployments first with `lep"
+                    " deployment remove`."
+                ),
+                (
+                    f"Photon id [red]{id_to_remove}[/] not removed. See error message"
+                    " above."
+                ),
                 exit_if_4xx=True,
             )
         return
@@ -283,8 +287,10 @@ def _find_deployment_name_or_die(conn: Connection, name, id, deployment_name):
     existing_names = set(d["name"] for d in deployments)
     check(
         deployment_name not in existing_names,
-        f"Deployment [red]{deployment_name}[/] already exists. please"
-        " choose another name.",
+        (
+            f"Deployment [red]{deployment_name}[/] already exists. please"
+            " choose another name."
+        ),
     )
     if not deployment_name:
         console.print("Attempting to find a proper deployment name.")
@@ -450,8 +456,11 @@ def run(
             id = _get_most_recent_photon_id_or_none(conn, name)
             if not id:
                 console.print(
-                    f"Photon [red]{name}[/] does not exist in the workspace. Did you"
-                    " intend to run a local photon? If so, please specify --local.",
+                    (
+                        f"Photon [red]{name}[/] does not exist in the workspace. Did"
+                        " you intend to run a local photon? If so, please specify"
+                        " --local."
+                    ),
                 )
                 sys.exit(1)
             console.print(f"Running the most recent version of [green]{name}[/]: {id}")
@@ -480,12 +489,18 @@ def run(
             sys.exit(1)
         explain_response(
             response,
-            f"Photon launched as [green]{deployment_name}[/]. Use `lep deployment"
-            f" status -n {deployment_name}` to check the status.",
-            f"Failed to launch photon as [red]{deployment_name}[/]. See error"
-            " message above.",
-            f"Failed to launch photon as [red]{deployment_name}[/]. Internal server"
-            " error.",
+            (
+                f"Photon launched as [green]{deployment_name}[/]. Use `lep deployment"
+                f" status -n {deployment_name}` to check the status."
+            ),
+            (
+                f"Failed to launch photon as [red]{deployment_name}[/]. See error"
+                " message above."
+            ),
+            (
+                f"Failed to launch photon as [red]{deployment_name}[/]. Internal server"
+                " error."
+            ),
         )
     else:
         # local execution
diff --git a/leptonai/cli/secret.py b/leptonai/cli/secret.py
index f91a430..1305dc9 100644
--- a/leptonai/cli/secret.py
+++ b/leptonai/cli/secret.py
@@ -49,8 +49,10 @@ def create(name, value):
     for n in name:
         check(
             not n.lower().startswith(LEPTON_RESERVED_ENV_PREFIX),
-            "Secret name cannot start with reserved prefix"
-            f" {LEPTON_RESERVED_ENV_PREFIX}. Found {n}.",
+            (
+                "Secret name cannot start with reserved prefix"
+                f" {LEPTON_RESERVED_ENV_PREFIX}. Found {n}."
+            ),
         )
     conn = get_connection_or_die()
     existing_secrets = api.list_secret(conn)
@@ -58,9 +60,11 @@ def create(name, value):
         for n in name:
             check(
                 n not in existing_secrets,
-                f"Secret with name [red]{n}[/] already exists. Please use a"
-                " different name or remove the existing secret with `lep secret"
-                " remove` first.",
+                (
+                    f"Secret with name [red]{n}[/] already exists. Please use a"
+                    " different name or remove the existing secret with `lep secret"
+                    " remove` first."
+                ),
             )
     response = api.create_secret(conn, name, value)
     explain_response(
diff --git a/leptonai/cli/storage.py b/leptonai/cli/storage.py
index 1f7a593..442b189 100644
--- a/leptonai/cli/storage.py
+++ b/leptonai/cli/storage.py
@@ -125,8 +125,10 @@ def rm(path):
     check(file_type is not None, f"[red]{path}[/] not found")
     check(
         file_type != "dir",
-        f"[red]{path}[/] is a directory. Use [red]rmdir {path}[/] to delete"
-        " directories.",
+        (
+            f"[red]{path}[/] is a directory. Use [red]rmdir {path}[/] to delete"
+            " directories."
+        ),
     )
 
     explain_response(
diff --git a/leptonai/cli/workspace.py b/leptonai/cli/workspace.py
index c334feb..32ba402 100644
--- a/leptonai/cli/workspace.py
+++ b/leptonai/cli/workspace.py
@@ -59,25 +59,31 @@ def login(
                 matching_ids.append(workspace_id)
         check(
             len(matching_ids) > 0,
-            f"No workspace with the given display name [red]{display_name}[/]"
-            " exists. Please first log in to the workspace using `lep workspace"
-            " login -i <workspace-id>`.",
+            (
+                f"No workspace with the given display name [red]{display_name}[/]"
+                " exists. Please first log in to the workspace using `lep workspace"
+                " login -i <workspace-id>`."
+            ),
         )
         check(
             len(matching_ids) == 1,
-            "Multiple workspaces with the given display name"
-            f" [red]{display_name}[/] exists. Note that display names may not be"
-            " unique - in this case, please log in with the workspace id using"
-            " `lep workspace login -i <workspace-id>`.",
+            (
+                "Multiple workspaces with the given display name"
+                f" [red]{display_name}[/] exists. Note that display names may not be"
+                " unique - in this case, please log in with the workspace id using"
+                " `lep workspace login -i <workspace-id>`."
+            ),
         )
         workspace_id = matching_ids[0]
     if test_only_workspace_url:
         check(
             workspace_id,
-            "Must specify --workspace-id if using --test-only-workspace-url. This"
-            " will create a new workspace login with the given workspace url. Also,"
-            " you should only use this if you are running unit tests for the Lepton"
-            " SDK.",
+            (
+                "Must specify --workspace-id if using --test-only-workspace-url. This"
+                " will create a new workspace login with the given workspace url. Also,"
+                " you should only use this if you are running unit tests for the Lepton"
+                " SDK."
+            ),
         )
         console.print("Using test-only workspace url for internal testing purposes.")
         console.print("Do not use this option unless you know what you are doing.")
diff --git a/leptonai/client.py b/leptonai/client.py
index ca0d40b..f43b2c0 100644
--- a/leptonai/client.py
+++ b/leptonai/client.py
@@ -250,11 +250,13 @@ class Client(object):
         # Check healthz to see if things are properly working
         if not self.healthz():
             self._debug_record.append(
-                "Client is not healthy - healthz() returned False. This might be"
-                " due to:\n- a nonstandard deployment that does not have a healthz"
-                " endpoint. In this case, you may ignore this warning.\n- a network"
-                " error. In this case, please check your network connection. You"
-                " may want to recreate the client for things to work properly.",
+                (
+                    "Client is not healthy - healthz() returned False. This might be"
+                    " due to:\n- a nonstandard deployment that does not have a healthz"
+                    " endpoint. In this case, you may ignore this warning.\n- a network"
+                    " error. In this case, please check your network connection. You"
+                    " may want to recreate the client for things to work properly."
+                ),
             )
 
         # At load time, we will also load the openapi specification.
diff --git a/leptonai/photon/tests/test_client_docgen.py b/leptonai/photon/tests/test_client_docgen.py
index 83a738b..bd84c85 100644
--- a/leptonai/photon/tests/test_client_docgen.py
+++ b/leptonai/photon/tests/test_client_docgen.py
@@ -154,8 +154,10 @@ class TestClientDocgen(unittest.TestCase):
         except RuntimeError as e:
             error_str = str(e)
             self.assertIn(
-                "Did you mean the following?\n    run5(\n        query='hello',\n  "
-                "      query2=1,\n    )",
+                (
+                    "Did you mean the following?\n    run5(\n        query='hello',\n  "
+                    "      query2=1,\n    )"
+                ),
                 error_str,
             )
```

**Comment by Yangqing** [comment] 2023-09-22 04:42
Ah thanks for confirming! Since the latest black passes lint, I'll close the issue for now. Appreciate your feedback.

**Closed by Yangqing** 2023-09-22 04:42 UTC
Labels: bug
